Add git hooks (#13)
* Rename executable scripts to .sh

* Add githooks

* Make more robust the sh scripts path calculation

* Add a formatting script for .gd files

* Add contributing notes

* Make sure scripts have mod=755

diff --git a/scripts/shared b/scripts/shared
--- a/scripts/shared
+++ b/scripts/shared
@@ -40,14 +40,21 @@ COLOR_INFO=${COLOR_LIGHT_BLUE}
 COLOR_NAME=${COLOR_GREEN}
 COLOR_VERSION=${COLOR_GREEN}
 COLOR_FILE=${COLOR_YELLOW}
-COLOR_LIST=${COLOR_DARK_GRAY}
+COLOR_DIM=${COLOR_DARK_GRAY}
 
 # Project root (in case scripts run from a different path)
-PROJECT_ROOT="$(realpath --relative-to "$(pwd)" "$(dirname "$0")/..")"
+if [ -n "${BASH_SOURCE:-}" ]; then
+  # Bash: use BASH_SOURCE to get sourced script path
+  thisPath="${BASH_SOURCE[0]}"
+else
+  # POSIX: fall back to $0 (might fail if sourced from .githooks)
+  thisPath="$0"
+fi
+PROJECT_ROOT="$(realpath --relative-to "$(pwd)" "$(dirname "${thisPath}")/..")"
 
 
 # Load configuration
-source "$(dirname "$0")/config"
+source "${PROJECT_ROOT}/scripts/config"
 
 
 #
@@ -106,5 +113,12 @@ require_godot() {
 require_gdlint() {
   if ! command -v "gdlint" >/dev/null 2>&1; then
     fail "gdlint can't be found" >&2
+  fi
+}
+
+# Check that gdformat is installed or fail if not available
+require_gdformat() {
+  if ! command -v "gdformat" >/dev/null 2>&1; then
+    fail "gdformat can't be found" >&2
   fi
 }
